//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestTours.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuestTours.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოგვწერეთ.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქართველო.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დღე.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დეტალები.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuestTours.ge  გთავაზობთ საუკეთესო ტურებს საქართველოში.
        /// </summary>
        public static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string MainText1 {
            get {
                return ResourceManager.GetString("MainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuestTours.ge გთავაზობთ საუკეთესო მომსახურებას.
        /// </summary>
        public static string MainTextServ {
            get {
                return ResourceManager.GetString("MainTextServ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string MainTextServ1 {
            get {
                return ResourceManager.GetString("MainTextServ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მეტი.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენი გალერეა.
        /// </summary>
        public static string OurGalley {
            get {
                return ResourceManager.GetString("OurGalley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენი სერვისი.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენი ტურები.
        /// </summary>
        public static string OurTours {
            get {
                return ResourceManager.GetString("OurTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფოტო გალერეა.
        /// </summary>
        public static string PhotoGallery {
            get {
                return ResourceManager.GetString("PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ლარი.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფასი.
        /// </summary>
        public static string PriceName {
            get {
                return ResourceManager.GetString("PriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სერვისები დეტალურად.
        /// </summary>
        public static string ServiceDetails {
            get {
                return ResourceManager.GetString("ServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტურები საქართველოში.
        /// </summary>
        public static string ToursinGeorgia {
            get {
                return ResourceManager.GetString("ToursinGeorgia", resourceCulture);
            }
        }
    }
}
