//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestTours.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuestToursEntities : DbContext
    {
        public GuestToursEntities()
            : base("name=GuestToursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryTranslated> CategoryTranslateds { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TourTranslated> TourTranslateds { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourPhoto> TourPhotoes { get; set; }
        public virtual DbSet<CategoryService> CategoryServices { get; set; }
        public virtual DbSet<CategoryServiceTranslated> CategoryServiceTranslateds { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesPhoto> ServicesPhotoes { get; set; }
        public virtual DbSet<ServicesTranslated> ServicesTranslateds { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SliderTranslated> SliderTranslateds { get; set; }
    }
}
