//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestTours.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesTranslated
    {
        public int Id { get; set; }
        public int TourID { get; set; }
        public string LangCode { get; set; }
        public string CategoryName { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string BigText { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Service Service { get; set; }
    }
}
